from gensim.models.keyedvectors import KeyedVectors

wordvectors_file_vec = './embeddings-l-model.vec'
cantidad = 100000
wordvectors = KeyedVectors.load_word2vec_format(wordvectors_file_vec, limit=cantidad)
print('Similitud entre los términos rey y mujer; definiendo género femenino:')

print(wordvectors.most_similar_cosmul(positive=['rey','mujer'],negative=['hombre']))
print('\n')
print('Similitud entre los términos actor y mujer; definiendo género femenino:')
print(wordvectors.most_similar_cosmul(positive=['actor','mujer'],negative=['hombre']))
print('\n')
print('Similitud entre los términos hijo y mujer; definiendo género femenino:')
print(wordvectors.most_similar_cosmul(positive=['hijo','mujer'],negative=['hombre']))
print('\n')
print('Similitud entre los términos yerno y mujer; definiendo género femenino:')
print(wordvectors.most_similar_cosmul(positive=['yerno','mujer'],negative=['hombre']))
print('\n')

print('Considerando Conjugaciones:')
print(wordvectors.most_similar_cosmul(positive=['jugar','canta'],negative=['cantar']))
print('\n')
print('Considerando Conjugaciones:')
print(wordvectors.most_similar_cosmul(positive=['jugar','cantaría'],negative=['cantar']))
print('\n')
print('Considerando Conjugaciones:')
print(wordvectors.most_similar_cosmul(positive=['ir','jugando'],negative=['jugar']))
print('\n')
print('Considerando Relaciones:')
print(wordvectors.most_similar_cosmul(positive=['santiago','venezuela'],negative=['chile']))
print('\n')
print('Considerando Relaciones:')
print(wordvectors.most_similar_cosmul(positive=['habana','chile'],negative=['santiago']))
print('\n')
print('Excluyendo al diferente:')
print(wordvectors.doesnt_match(['blanco','azul','rojo','chile']))
print('\n')
print('Representación Vectorial:')
print(wordvectors['hola'])